# Generated by Django 4.2.2 on 2026-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Отметьте, чтобы опубликовать продукт", verbose_name="Опубликован"
            ),
        ),
    ]
