# Generated by Django 4.2.2 on 2026-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Token"),
        ),
    ]
